[Firefox] fix session cookie retrieval under first-party isolation
Setup no longer errors when `privacy.firstparty.isolate` is enabled, as
is the default in Tor Browser:

```
checkForSession - background.js:165:41
Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set.
```